barterportal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
]

main_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('items', views.ItemsList.as_view(), name='index'),
    path('items/myitems/', views.MyItemsList.as_view(), name='items_myitems'),
    path('items/create/', views.ItemCreate.as_view(), name='item_create'),
    path('items/<int:pk>/update/', views.ItemUpdate.as_view(), name='item_update'),
    path('items/<int:pk>/delete/', views.ItemDelete.as_view(), name='item_delete'),
    path('items/<int:pk>/',views.ItemDetail.as_view(), name="item_detail"),
    path('items/<int:item_id>/add_photo/', views.add_photo, name='add_photo'),
    path('items/filter', views.filter_items_list, name='filter'),
    path('trades/', views.TradeList.as_view(), name='trades_index' ),
    path('trades/<int:pk>', views.TradeDetail.as_view(), name='trade_detail'),
    path('trades/create/<int:item_id>',views.TradeCreate.as_view(), name ='trade_create'),
    path('trades/<int:trade_id>/approve/', views.trade_approve, name = 'trade_approve'),
    path('trades/<int:trade_id>/reject/', views.trade_reject, name = 'trade_reject'),
    path('trades/<int:pk>/delete/', views.TradeDelete.as_view(), name='trade_delete'),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/login/', views.Login.as_view()),

]


main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

ITEM_STATUS=(
    ('1','Ready to Trade'),
    ('2','Traded')
)
TRADE_STATUS=(
    ('1','Proposed'),
    ('2','Approved'),
    ('3','Denied')
)
CATEGORY_STATUS=(
    ('Clothing', 'Clothing'),
    ('Electronics', 'Electronics'),
    ('Sporting Goods', 'Sporting Goods'),
    ('Jewelry', 'Jewelry'),
    ('Entertainment', 'Entertainment'),
    ('Other', 'Other')
)

# Create your models here.

class Item(models.Model):
    name=models.CharField(max_length=150)
    description=models.CharField(max_length=500)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    category=models.CharField(
        max_length=15,
        choices=CATEGORY_STATUS,
        default=CATEGORY_STATUS[0][0]
    )
    status=models.CharField(
        max_length=1,
        choices=ITEM_STATUS,
        default=ITEM_STATUS[0][0]
    )
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('item_detail',  kwargs={'pk': self.id})
    
class Trade(models.Model):
    item_primary=models.ForeignKey(Item, related_name="trade_primary", on_delete=models.CASCADE)
    item_proposed=models.ForeignKey(Item, related_name="trade_proposed", on_delete=models.CASCADE)
    comment=models.CharField(max_length=1000, blank=True)
    status=models.CharField(
        max_length=1,
        choices=TRADE_STATUS,
        default=TRADE_STATUS[0][0]
    )
    def __str__(self):
        return f"trade {self.item_primary} for {self.item_proposed}"
    def get_absolute_url(self):
        return reverse('trades_index')
    
class Photo(models.Model):
    url = models.CharField(max_length=200)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    def __str__(self):
        return f"Photo for item_id: {self.item_id} @{self.url}"
    
    

main_app/forms.py
from django.contrib.auth.forms import AuthenticationForm, UsernameField, UserCreationForm
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import Item, Trade

class ItemForm(ModelForm):
   photo = forms.FileField(label='uplaod a photo')

   class Meta:
      model = Item 
      fields = ['name', 'description', 'category']

   def __init__(self, *args, **kwargs):
        super(ItemForm, self).__init__(*args, **kwargs)
        self.fields['photo'].required = False
   
   name = forms.CharField(label= '', widget=forms.TextInput(attrs={'placeholder': 'item name'}))
   description = forms.CharField(label= '', widget=forms.TextInput(attrs={'placeholder': 'item description'}))


class TradeForm(ModelForm):
   class Meta:
      model = Trade
      fields = ['item_proposed', 'comment']
      labels = {'item_proposed' : 'select the item you would like to trade:'}
   
   comment = forms.CharField(label= '', widget=forms.TextInput(attrs={'placeholder': 'comments for trade'}))

   def __init__(self, *args, **kwargs):
      user = kwargs.pop('user')
      super(TradeForm, self).__init__(*args, **kwargs)
      self.fields['item_proposed'].queryset = Item.objects.filter(user = user).exclude(status = '2')

class UserSignUpForm(UserCreationForm):
   class Meta:
      model = User
      fields = ['username', 'password1', 'password2']
   
   username = UsernameField(widget=forms.TextInput(attrs={'placeholder': 'username'}), label='', help_text = '150 characters or fewer. Letters, digits and @/./+/-/_ only.')
   password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'password'}), label='', help_text = 'Your password can’t be entirely numeric.')
   password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'password confirmation'}), label='')

class UserLoginForm(AuthenticationForm):
  def __init__(self, *args, **kwargs):
     super(UserLoginForm, self).__init__(*args, **kwargs)

  username = UsernameField(widget=forms.TextInput(attrs={'placeholder': 'username'}), label='')
  password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'password'}), label='')

main_app/views.py
import uuid
import boto3
import os
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Item, Trade, Photo
from .forms import UserSignUpForm, UserLoginForm, TradeForm, ItemForm


def index(request):
    return render(request, 'home.html')

class ItemsList(ListView):
  model = Item

  def get_context_data(self, **kwargs):
    context = super(ItemsList, self).get_context_data(**kwargs)
    items = []
    if self.request.user.is_authenticated :
      items = Item.objects.exclude(user = self.request.user).exclude(status = '2')
    else :
      items = Item.objects.all().exclude(status = '2')
    context['item_list'] = items
    return context

class MyItemsList(LoginRequiredMixin,ListView):
  model = Item
  template_name = 'items/my_items.html'
  
  def get_context_data(self, **kwargs):
    context = super(MyItemsList, self).get_context_data(**kwargs)
    context['items'] = Item.objects.filter(user = self.request.user).exclude(status = '2')
    context['items_traded'] = Item.objects.filter(user = self.request.user).filter(status = '2')
    return context
  
class ItemCreate(LoginRequiredMixin, CreateView):
  model = Item
  form_class = ItemForm

  def form_valid(self, form):
    form.instance.user = self.request.user
    result = super().form_valid(form)
    add_photo(self.request.FILES.get('photo', None),self.object.pk)
    return result
  
class ItemUpdate(LoginRequiredMixin, UpdateView):
  model = Item
  form_class = ItemForm

  def form_valid(self, form):
    result = super().form_valid(form)
    if self.request.FILES.get('photo', None):
      add_photo(self.request.FILES.get('photo', None),self.object.pk)
    return result

class ItemDelete(LoginRequiredMixin, DeleteView):
  model = Item
  success_url = '/items/myitems'

class ItemDetail(DetailView):
  model= Item

  def dispatch(self, request, *args, **kwargs):
    self.id = kwargs['pk']
    return super().dispatch(request, *args, **kwargs)

  def get_context_data(self, **kwargs):
    context = super(ItemDetail, self).get_context_data(**kwargs)
    active_trade_primary = Trade.objects.filter(item_primary=self.id).filter(status='1')
    active_trade_proposed = Trade.objects.filter(item_proposed=self.id).filter(status='1')
    context['active_trade_primary'] = active_trade_primary
    context['active_trade_proposed'] = active_trade_proposed
    return context  



class TradeDetail(LoginRequiredMixin, DetailView):
  model = Trade

class TradeCreate(LoginRequiredMixin, CreateView):
  model = Trade
  form_class = TradeForm

  def get_form_kwargs(self):
    kwargs = super(TradeCreate, self).get_form_kwargs()
    kwargs['user'] = self.request.user
    return kwargs

  def dispatch(self, request, *args, **kwargs):
    self.item_primary = get_object_or_404(Item, pk=kwargs['item_id'])
    return super().dispatch(request, *args, **kwargs)

  def form_valid(self, form):
    form.instance.item_primary = self.item_primary
    return super().form_valid(form)

class TradeList(LoginRequiredMixin, ListView):
  model = Trade
  def get_context_data(self, **kwargs):
    context = super(TradeList, self).get_context_data(**kwargs)
    trades_pending = []
    trades_closed = []
    for trade in Trade.objects.all():
      if trade.item_primary.user == self.request.user or trade.item_proposed.user == self.request.user:
        if trade.status == '1':
          trades_pending.append(trade)
        elif trade.status == '2':
          trades_closed.append(trade)
    context['trade_list_pending'] = trades_pending
    context['trade_list_closed'] = trades_closed
    return context


class TradeDelete(LoginRequiredMixin, DeleteView):
  model = Trade
  success_url = '/trades'

@login_required
def trade_approve(request, trade_id):
  trade = Trade.objects.get(id=trade_id)
  trade.status = '2'
  trade.save()
  item_primary = Item.objects.get(id=trade.item_primary.id)
  item_primary.status = '2'
  item_primary.save()
  item_proposed = Item.objects.get(id=trade.item_proposed.id)
  item_proposed.status = '2'
  item_proposed.save()
  return redirect('trades_index')

@login_required
def trade_reject(request, trade_id):
  trade = Trade.objects.get(id=trade_id)
  trade.status = '3'
  trade.save()
  return redirect('trades_index')

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserSignUpForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserSignUpForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

class Login(LoginView):
  authentication_form = UserLoginForm

def add_photo(photo_file, item_id):
  s3 = boto3.client('s3')
  # need a unique "key" for S3 / needs image file extension too
  key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
  # just in case something goes wrong
  try:
      bucket = os.environ['S3_BUCKET']
      s3.upload_fileobj(photo_file, bucket, key)
      # build the full url string
      url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
      # we can assign to cat_id or cat (if you have a cat object)
      Photo.objects.create(url=url, item_id=item_id)
  except Exception as e:
      print('An error occurred uploading file to S3')
      print(e)
  return redirect('item_detail', pk=item_id)

def filter_items_list(request):
  if request.user.is_authenticated:
    item_list = Item.objects.exclude(user = request.user).exclude(status = '2').filter(category = request.POST['CATEGORIES'])
  else :
    item_list = Item.objects.all().exclude(status = '2').filter(category = request.POST['CATEGORIES'])
  return render(request, 'main_app/item_list.html', {
    'item_list': item_list
  })

main_app/templates/main_app/item_confirm_delete.html
{% extends 'base.html' %}
{% block title %}<title>Confirm Delete</title>{% endblock %}
{% block content %}
<div class="item-detail-container">
  <h1>Delete Item</h1>

  <h4>Are you sure you want to delete <span class="spc-bold">{{ item.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn dark-grn-bckgrnd">
    <a href="{% url 'items_myitems' %}" class="btn tan-bckgrnd" >Cancel</a>
  </form>
</div>
{% endblock %}

main_app/templates/main_app/item_detail.html
{% extends 'base.html' %}
{% block title %}<title>Item Detail</title>{% endblock %}
{% block bodytag %} class="home" {% endblock %}
{% block content %}

<div class="item-detail-container flex">
    <div class="item-left">
        <div class="item-detail-img-container flex">
            {% if item.photo_set.count %}
                {% with item.photo_set.all|first as image %}
                <div class="gallery-arrows"><a href="#" id="arrow-left"><h1><</h1></a></div>
                    <img src="{{image.url}}" id="cur-img" data-img-id="{{image.id}}">
                <div class="gallery-arrows"><a href="#" id="arrow-right"><h1>></h1></a></div>
                {% endwith %}
            {% else %}
            <img src="https://i0.wp.com/sofiestdesigns.com/wp-content/uploads/2022/05/SilverMushroom.jpg?fit=768%2C768&ssl=1">
            {% endif %}
        </div>
        <div class="flex img-gallery-sm" id="img-gallery">   
            {% for image in item.photo_set.all %}
                <div class="center-container"><img src="{{image.url}}" data-gallery-img-id="{{image.id}}"></div>
            {% endfor %}
        </div>
    </div>
    <div class="item-right">
        {% if active_trade_primary.count or active_trade_proposed.count %}
            <div class="marquee">
                <ul class="marquee-content">
                    <li>trade in progress</li>
                </ul>
                <ul class="marquee-content" aria-hidden="true">
                    <li>trade in progress</li>
                </ul>
            </div>
        {% elif item.status == '2' %}
            <div class="item-traded">{{item.get_status_display}}</div>
        {% endif %}
        <div class="item-detail-text">
            <div><h1>{{item.name}}</h1></div>
            <div><h3>posted by: {{item.user}}</h3></div>
            <div>{{item.description}}</div>
        </div>
        <div class="item-btns">
            {% for trade in item.trade_primary.all %}
            <div class="item-detail-curtrade-detail">
                <div>Trade Status: {{trade.get_status_display}}</div>
                <div>Trade Initiated By: {{trade.item_proposed.user}}</div>
                <div>Trade For: 
                    <a href="{% url 'item_detail' trade.item_proposed.id%}" class="decorate-anchor">{{trade.item_proposed}}</a>
                </div>
                <div>Comments: {% if trade.comment %} {{trade.comment}} {% else %} no comment {% endif%}</div>
                <div><a href="{% url 'trade_detail' trade.id %}" class="decorate-anchor">click for trade details</a></div>
            </div>
                {% if item.user == user and not item.status == '2' %}
                <div class="btn-container"><a href="{% url 'trade_approve' trade.id %}"><div class="btn dark-grn-bckgrnd">APPROVE TRADE</div></a></div>
                <div class="btn-container"><a href="{% url 'trade_reject' trade.id %}"><div class="btn dark-grn-bckgrnd">REJECT TRADE</div></a></div>
                {% endif %}
            {% empty %}
                {% if item.user == user and not item.status == '2' and active_trade_proposed.count == 0 %}
                <div class="btn-container"><a href="{% url 'item_update' item.id %}"><div class="btn dark-grn-bckgrnd">EDIT</div></a></div>
                <div class="btn-container"><a href="{% url 'item_delete' item.id %}"><div class="btn dark-grn-bckgrnd">DELETE</div></a></div>
                {% endif %}
            {% endfor %}
            {% for trade in active_trade_proposed %}
                <div class="item-detail-curtrade-detail">
                    <div>Trade Status: {{trade.get_status_display}}</div>
                    <div>Trade Initiated By: {{trade.item_proposed.user}}</div>
                    <div>Trade For: 
                        {% if trade.item_proposed.id == item.id %} 
                            <a href="{% url 'item_detail' trade.item_primary.id%}" class="decorate-anchor">{{ trade.item_primary }} </a>
                        {% else %} 
                            <a href="{% url 'item_detail' trade.item_proposed.id%}" class="decorate-anchor">{{trade.item_proposed }}</a>
                        {% endif %}
                        </a>
                    </div>
                    <div>Comments: {% if trade.comment %} {{trade.comment}} {% else %} no comment {% endif%}</div>
                    <div><a href="{% url 'trade_detail' trade.id %}" class="decorate-anchor">click for trade details</a></div>
                </div>
            {% endfor %}
            {% if not item.user == user and active_trade_proposed.count == 0 %}
            <div class="btn-container"><a href="{% url 'trade_create' item.id %}"><div class="btn dark-grn-bckgrnd">TRADE FOR THIS ITEM</div></a></div>
            {% endif %}
        </div>
    </div>
</div>


{% endblock %}

main_app/templates/main_app/item_form.html
{% extends 'base.html' %}
{% block title %}<title>New Item</title>{% endblock %}
{% block bodytag %} class="home" {% endblock %}
{% block content %}

<div class="item-detail-container flex center-container">
    <form action="" method="POST" enctype="multipart/form-data" class="login-form">
        {% csrf_token %}
            {{ form.as_p }}
        {% if object %}
        <input type="submit" value="update item"  class="btn dark-grn-bckgrnd ">
        {% else %}
        <input type="submit" value="create item"  class="btn dark-grn-bckgrnd ">
        {% endif %}
    </form>
</div>

{% endblock %}

main_app/templates/main_app/item_list.html
{% extends 'base.html' %}
{% block title %}<title>items for barter</title>{% endblock %}
{% block bodytag %} class="items-index" {% endblock %}
{% block content %}

<div class="flex spc-btwn">
    <div class="tab-container">
        <div class="tab-text"><h1>TRADE</h1></div>
    </div>
    
    <div class="category-container">
        <div>
            <div>CATEGORIES</div>
            <form action="{% url 'filter' %}" method="POST">
                {% csrf_token %}
                <select name="CATEGORIES">
                    <option value="Clothing">Clothing</option>
                    <option value="Electronics">Electronics</option>
                    <option value="Sporting Goods">Sporting Goods</option>
                    <option value="Jewelry">Jewelry</option>
                    <option value="Entertainment">Entertainment</option>
                    <option value="Other">Other</option>
                </select>
                <input type="submit" value="filter" class="btn-sm tan-bckgrnd">
            </form>  
        </div>
    </div>
</div>


<div class="items-container">
    <div class="items-grid">
        {% for item in item_list %}
        <a href="{% url 'item_detail' item.id %}">
            <div class="item-container">
                {% if item.photo_set.count %}
                <div class="item-img-container extra">
                    {% with item.photo_set.all|first as image %}
                    <img src="{{image.url}}">
                    {% endwith %}
                </div>
                {% else %}
                <div class="item-img-container extra">
                    <img src="https://i0.wp.com/sofiestdesigns.com/wp-content/uploads/2022/05/SilverMushroom.jpg?fit=768%2C768&ssl=1">
                </div>                
                {% endif %}
                <div class="img-text-container">
                    <h3>{{item.name|upper}}</h3>
                </div>
            </div>
        </a>
        {% empty %}
        <div>no items</div>
        {% endfor%}
    </div>
</div>

{% endblock %}

main_app/templates/main_app/trade_confirm_delete.html
{% extends 'base.html' %}
{% block title %}<title>Confirm Trade Withdraw</title>{% endblock %}
{% block content %}

<div class="item-detail-container">
  <h1>Withdraw Trade</h1>

  <h4>Are you sure you want to withdraw the <span class="spc-bold">{{ trade }}</span>? This action is final and cannot be undone.</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Withdraw!"  class="btn dark-grn-bckgrnd">
    
    <a href="{% url 'trade_detail' trade.id %}" class="btn tan-bckgrnd">Cancel</a>
  </form>
</div>

{% endblock %}

main_app/templates/main_app/trade_detail.html
{% extends 'base.html' %}
{% block title %}<title>trade details</title>{% endblock %}
{% block bodytag %} class="items-index" {% endblock %}
{% block content %}

<div class="tab-container">
    <div class="tab-text"><h1>{{trade}}</h1></div>
</div>
<div class="items-container">
    <h3>Trade Status: {{trade.get_status_display}}</h3>
    <div>Trade For: 
        <a href="{% url 'item_detail' trade.item_primary.id %}" class="decorate-anchor">{{trade.item_primary}}</a>
        (item posted by {{trade.item_primary.user}})
    </div>
    <div>Initiated By: {{trade.item_proposed.user}}</div>
    <div>Proposed Trade Item: <a href="{% url 'item_detail' trade.item_proposed.id %}" class="decorate-anchor">{{trade.item_proposed}}</a></div>
    {% if trade.comment %}
    <div>Trade Comments: {{trade.comment}}</div>
    {% endif %}
    {% if trade.status == '1' %}
        {% if trade.item_primary.user == user %}
            <div>
                <div class="btn-container upper-margin ">
                    <a href="{% url 'trade_approve' trade.id %}">
                        <div class="btn dark-grn-bckgrnd">APPROVE</div>
                    </a>
                </div>
                <div class="btn-container upper-margin ">
                    <a href="{% url 'trade_reject' trade.id %}">
                        <div class="btn dark-grn-bckgrnd">REJECT</div>
                    </a>
                </div>
            </div>
        {% elif trade.item_proposed.user == user %}
            <div class="btn-container upper-margin">
                <a href="{% url 'trade_delete' trade.id %}">
                    <div class="btn dark-grn-bckgrnd">Withdraw Trade</div>
                </a>
            </div>
        {% endif %}
    {% endif %}
</div>

{% endblock %}

main_app/templates/main_app/trade_form.html
{% extends 'base.html' %}
{% block title %}<title>New Trade</title>{% endblock %}
{% block bodytag %} class="items-index" {% endblock %}
{% block content %}

<div class="item-detail-container flex center-container">

<form action="" method="POST" class="login-form">
    {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="create"   class="btn dark-grn-bckgrnd ">
</form>

</div>

{% endblock %}

main_app/templates/main_app/trade_list.html
{% extends 'base.html' %}
{% block title %}<title>trade history</title>{% endblock %}
{% block bodytag %} class="items-index" {% endblock %}
{% block content %}

<div class="tab-container">
    <div class="tab-text"><h1>PENDING TRADES</h1></div>
</div>
<div class="items-container">
    {% for trade in trade_list_pending %}
    <div class="trade-in-progress">
        <div>Item I'm Getting: 
            {% if trade.item_primary.user == user %} 
                <a href="{% url 'item_detail' trade.item_proposed.id %}" class="decorate-anchor">{{trade.item_proposed}} </a>
            {% else %} 
                <a href="{% url 'item_detail' trade.item_primary.id %}" class="decorate-anchor">{{trade.item_primary}} </a>
            {% endif %}
        </div>
        <div> Item I'm Giving:
            {% if trade.item_proposed.user == user %} 
            <a href="{% url 'item_detail' trade.item_proposed.id %}" class="decorate-anchor">{{trade.item_proposed}} </a>
            {% else %} 
            <a href="{% url 'item_detail' trade.item_primary.id %}" class="decorate-anchor">{{trade.item_primary}} </a>
            {% endif %}
        </div>
        <div> Action Pending: 
            {% if trade.item_primary.user == user %} 
                <a href="{% url 'trade_detail' trade.id %}" class="decorate-anchor">you- click here to review and approve or reject this trade</a>
            {% else %}
                {{trade.item_primary.user}}
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>
<div class="trades-container">
    <h1>COMPLETED TRADES</h1>
</div>
<div class="trades-container">
    {% for trade in trade_list_closed %}
    <div class="trade-done">
        <div>What I Got: 
            {% if trade.item_primary.user == user %} 
                <a href="{% url 'item_detail' trade.item_proposed.id %}" class="decorate-anchor">{{trade.item_proposed}} </a>
            {% else %} 
                <a href="{% url 'item_detail' trade.item_primary.id %}" class="decorate-anchor">{{trade.item_primary}} </a>
            {% endif %}
        </div>
        <div> What I Gave:
            {% if trade.item_proposed.user == user %} 
            <a href="{% url 'item_detail' trade.item_proposed.id %}" class="decorate-anchor">{{trade.item_proposed}} </a>
            {% else %} 
            <a href="{% url 'item_detail' trade.item_primary.id %}" class="decorate-anchor">{{trade.item_primary}} </a>
            {% endif %}
        </div>
        <div> <a href="{% url 'trade_detail' trade.id %}" class="decorate-anchor">click to see trade details</a> </div>
    </div>
    {% endfor %}
</div>

{% endblock %}